# Generated by Django 3.2.18 on 2023-04-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField(unique=True)),
                ('name', models.CharField(default='Name of recipe', max_length=255)),
                ('ingridients', models.TextField(default='Ingredients list not found, but will be soon...')),
                ('image', models.ImageField(blank=True, default='default_value', null=True, upload_to='recipes/media')),
                ('cooking_steps', models.TextField(default='Steps not found, but will be soon...')),
                ('sourceUrl', models.URLField(blank=True, default='https://spoonacular.com/', null=True)),
                ('save_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
