# Generated by Django 3.2.18 on 2023-06-08 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField(unique=True)),
                ('name', models.CharField(default='Name of recipe', max_length=255)),
                ('ingridients', models.TextField(default='Ingredients list not found, but will be soon...')),
                ('image', models.ImageField(blank=True, default='default_value', null=True, upload_to='recipes/media')),
                ('cooking_steps', models.TextField(default='Steps not found, but will be soon...')),
                ('cooking_time', models.TextField(default='Time not found, but will be soon...')),
                ('sourceUrl', models.URLField(blank=True, default='https://spoonacular.com/', null=True)),
                ('save_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
