# Generated by Django 3.2.18 on 2023-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_recipes', '0002_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.TextField(default='Time not found, but will be soon...'),
        ),
    ]
